name = "PessimisticLearning"
uuid = "27fc195e-2997-46dd-b0ef-9c66dbef8ce1"
authors = ["aureliano <datadreamscorp@protonmail.com>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
